### ISSUE TITLE
Maze generation

### ISSUE THREAD

**Issue by kishorbhat** [therealkbhat/mazerunner#1]
Write a maze-generation algorithm to give the player new mazes on each run.

Resources:
- [Wikipedia](https://en.wikipedia.org/wiki/Maze_generation_algorithm)
- [Maze Generation Algorithm Recap](http://weblog.jamisbuck.org/2011/2/7/maze-generation-algorithm-recap)

**Comment by JonnoFTW** [comment]
I wrote a maze generator for one of my projects, I'll try to copy it over for you.

**Comment by kishorbhat** [comment]
Resolved in #7.
