### ISSUE TITLE
Fix bug in collision

### ISSUE THREAD

**Issue by kishorbhat** [therealkbhat/mazerunner#8]
If a troll hits you in `moveTrolls()`, the appropriate message is displayed and exit takes place.

However, a player can walk over a troll and it gets removed. The game proceeds normally. This is erroneous behaviour; the game should end whether it is the troll that moves onto the player or the other way around.

A simple check in `updatePlayerPosition()` to see if the troll and player coordinates match should do the trick.

**Comment by erguven** [comment]
Hey, I'm on it.

**Comment by kishorbhat** [comment]
Resolved in #9.
